/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BangumiSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/bangumi/types.ts
var BANGUMI_COLLECTION_TYPES = {
  wish: 1,
  collect: 2,
  do: 3,
  onHold: 4,
  dropped: 5
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  accessToken: "",
  username: "",
  syncDirectory: "Bangumi/Anime",
  collectionTypes: [BANGUMI_COLLECTION_TYPES.do],
  userAgent: "zhaoyuanhua/bangumi-sync/0.1.0 (Obsidian Plugin)"
};
var COLLECTION_OPTIONS = [
  {
    key: BANGUMI_COLLECTION_TYPES.wish,
    label: "Wish",
    description: "Sync subjects marked as want to watch."
  },
  {
    key: BANGUMI_COLLECTION_TYPES.collect,
    label: "Collected",
    description: "Sync subjects marked as watched."
  },
  {
    key: BANGUMI_COLLECTION_TYPES.do,
    label: "Watching",
    description: "Sync subjects currently in progress."
  },
  {
    key: BANGUMI_COLLECTION_TYPES.onHold,
    label: "On hold",
    description: "Sync subjects marked as on hold."
  },
  {
    key: BANGUMI_COLLECTION_TYPES.dropped,
    label: "Dropped",
    description: "Sync subjects marked as dropped."
  }
];
var BangumiSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bangumi Sync" });
    new import_obsidian.Setting(containerEl).setName("Access token").setDesc("Paste a Bangumi access token. OAuth setup will be added later.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Bearer token").setValue(this.plugin.settings.accessToken).onChange(async (value) => {
        this.plugin.settings.accessToken = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Username").setDesc("Optional. If empty, the plugin will use /v0/me when syncing.").addText(
      (text) => text.setPlaceholder("Bangumi username").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync directory").setDesc("Notes will be created under this folder.").addText(
      (text) => text.setPlaceholder("Bangumi/Anime").setValue(this.plugin.settings.syncDirectory).onChange(async (value) => {
        this.plugin.settings.syncDirectory = value.trim() || "Bangumi/Anime";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("User-Agent").setDesc("Bangumi requires API clients to identify themselves.").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.userAgent).setValue(this.plugin.settings.userAgent).onChange(async (value) => {
        this.plugin.settings.userAgent = value.trim() || DEFAULT_SETTINGS.userAgent;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Collection statuses" });
    for (const option of COLLECTION_OPTIONS) {
      new import_obsidian.Setting(containerEl).setName(option.label).setDesc(option.description).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.collectionTypes.includes(option.key)).onChange(async (enabled) => {
          const selected = new Set(this.plugin.settings.collectionTypes);
          if (enabled) {
            selected.add(option.key);
          } else {
            selected.delete(option.key);
          }
          this.plugin.settings.collectionTypes = Array.from(selected);
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// src/bangumi/client.ts
var import_obsidian2 = require("obsidian");
var BangumiClient = class {
  constructor(options) {
    this.options = options;
    this.baseUrl = "https://api.bgm.tv";
  }
  async getMe() {
    return this.request("/v0/me");
  }
  async getCollections(params) {
    var _a, _b;
    const search = new URLSearchParams({
      subject_type: String(params.subjectType),
      type: String(params.collectionType),
      limit: String((_a = params.limit) != null ? _a : 50),
      offset: String((_b = params.offset) != null ? _b : 0)
    });
    return this.request(
      `/v0/users/${encodeURIComponent(params.username)}/collections?${search.toString()}`
    );
  }
  async getSubjectEpisodeCollections(subjectId) {
    return this.request(
      `/v0/users/-/collections/${subjectId}/episodes`
    );
  }
  async request(path) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.baseUrl}${path}`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${this.options.accessToken}`,
        "User-Agent": this.options.userAgent
      }
    });
    if (response.status < 200 || response.status >= 300) {
      const detail = response.text ? ` ${response.text}` : "";
      throw new Error(
        `Bangumi API request failed: ${response.status}${detail}`
      );
    }
    return response.json;
  }
};

// src/sync/markdown-renderer.ts
var SYNC_BLOCK_START = "<!-- bangumi-sync-start -->";
var SYNC_BLOCK_END = "<!-- bangumi-sync-end -->";
var MarkdownRenderer = class {
  renderSubjectNote(subject) {
    var _a, _b, _c, _d, _e, _f, _g;
    const bangumiSubject = subject.collection.subject;
    const title = bangumiSubject.name_cn || bangumiSubject.name;
    const cover = ((_a = bangumiSubject.images) == null ? void 0 : _a.large) || ((_b = bangumiSubject.images) == null ? void 0 : _b.common);
    const rating = (_c = subject.collection.rate) != null ? _c : "";
    const updatedAt = (_d = subject.collection.updated_at) != null ? _d : "";
    const status = this.renderCollectionStatus(subject.collection.type);
    const tags = (_e = subject.collection.tags) != null ? _e : [];
    const comment = (_f = subject.collection.comment) != null ? _f : "";
    return [
      "---",
      `bangumi_id: ${bangumiSubject.id}`,
      "type: anime",
      `collection_type: ${subject.collection.type}`,
      `status: ${status}`,
      `rating: ${rating}`,
      `eps_total: ${(_g = bangumiSubject.eps) != null ? _g : ""}`,
      `updated_at: ${JSON.stringify(updatedAt)}`,
      `bangumi_tags: ${JSON.stringify(tags)}`,
      `comment: ${JSON.stringify(comment)}`,
      "tags:",
      "  - bangumi",
      "  - anime",
      "---",
      "",
      `# ${title}`,
      "",
      SYNC_BLOCK_START,
      "",
      cover ? `![](${cover})` : "",
      "",
      "## Progress",
      "",
      this.renderEpisodeChecklist(subject),
      "",
      "## Bangumi",
      "",
      `- Subject ID: ${bangumiSubject.id}`,
      `- Status: ${status}`,
      `- User rating: ${rating || "N/A"}`,
      `- Original title: ${bangumiSubject.name}`,
      bangumiSubject.date ? `- Air date: ${bangumiSubject.date}` : "",
      bangumiSubject.eps ? `- Episodes: ${bangumiSubject.eps}` : "",
      tags.length > 0 ? `- User tags: ${tags.join(", ")}` : "",
      comment ? `- User comment: ${comment}` : "",
      "",
      SYNC_BLOCK_END,
      "",
      "## Notes",
      ""
    ].filter((line) => line !== null).join("\n");
  }
  mergeSyncedBlock(existingContent, nextContent) {
    const start = existingContent.indexOf(SYNC_BLOCK_START);
    const end = existingContent.indexOf(SYNC_BLOCK_END);
    if (start === -1 || end === -1 || end < start) {
      return nextContent;
    }
    const nextStart = nextContent.indexOf(SYNC_BLOCK_START);
    const nextEnd = nextContent.indexOf(SYNC_BLOCK_END);
    if (nextStart === -1 || nextEnd === -1 || nextEnd < nextStart) {
      return existingContent;
    }
    const before = existingContent.slice(0, start);
    const after = existingContent.slice(end + SYNC_BLOCK_END.length);
    const syncedBlock = nextContent.slice(nextStart, nextEnd + SYNC_BLOCK_END.length);
    return `${before}${syncedBlock}${after}`;
  }
  renderEpisodeChecklist(subject) {
    if (subject.episodeSyncError) {
      return `- [ ] Episode progress unavailable: ${subject.episodeSyncError}`;
    }
    if (subject.episodes.length === 0) {
      return "- [ ] Episode progress unavailable.";
    }
    return subject.episodes.map((item) => {
      const episode = item.episode;
      const checked = item.type > 0 ? "x" : " ";
      const title = episode.name_cn || episode.name || `Episode ${episode.sort}`;
      return `- [${checked}] EP${episode.sort} ${title}`;
    }).join("\n");
  }
  renderCollectionStatus(type) {
    switch (type) {
      case 1:
        return "wish";
      case 2:
        return "collect";
      case 3:
        return "do";
      case 4:
        return "on_hold";
      case 5:
        return "dropped";
      default:
        return String(type);
    }
  }
};

// src/sync/note-writer.ts
var import_obsidian3 = require("obsidian");
var NoteWriter = class {
  constructor(app, renderer) {
    this.app = app;
    this.renderer = renderer;
  }
  async writeSubjectNote(syncDirectory, subject) {
    const existing = this.findExistingSubjectNote(
      subject.collection.subject.id,
      syncDirectory
    );
    const rendered = this.renderer.renderSubjectNote(subject);
    if (existing) {
      const previous = await this.app.vault.read(existing);
      await this.app.vault.modify(
        existing,
        this.renderer.mergeSyncedBlock(previous, rendered)
      );
      return existing;
    }
    const directory = (0, import_obsidian3.normalizePath)(syncDirectory);
    await this.ensureFolder(directory);
    const title = subject.collection.subject.name_cn || subject.collection.subject.name;
    const path = (0, import_obsidian3.normalizePath)(
      `${directory}/${this.toSafeFileName(title)} [bgm-${subject.collection.subject.id}].md`
    );
    const existingAtPath = this.app.vault.getAbstractFileByPath(path);
    if (existingAtPath instanceof import_obsidian3.TFile) {
      const previous = await this.app.vault.read(existingAtPath);
      await this.app.vault.modify(
        existingAtPath,
        this.renderer.mergeSyncedBlock(previous, rendered)
      );
      return existingAtPath;
    }
    return this.app.vault.create(path, rendered);
  }
  findExistingSubjectNote(subjectId, syncDirectory) {
    var _a, _b;
    const directory = (0, import_obsidian3.normalizePath)(syncDirectory);
    const idMarker = `[bgm-${subjectId}]`;
    return (_b = (_a = this.app.vault.getMarkdownFiles().find(
      (file) => {
        var _a2, _b2;
        return file.path.startsWith(`${directory}/`) && String(
          (_b2 = (_a2 = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a2.frontmatter) == null ? void 0 : _b2.bangumi_id
        ) === String(subjectId);
      }
    )) != null ? _a : this.app.vault.getMarkdownFiles().find(
      (file) => file.path.startsWith(`${directory}/`) && (file.basename.includes(idMarker) || file.basename.includes(String(subjectId)))
    )) != null ? _b : null;
  }
  async ensureFolder(path) {
    const parts = path.split("/");
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  toSafeFileName(value) {
    return value.replace(/[\\/:*?"<>|]/g, "_").trim() || "Untitled";
  }
};

// src/sync/sync-service.ts
var ANIME_SUBJECT_TYPE = 2;
var PAGE_LIMIT = 50;
var SyncService = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async sync() {
    if (!this.settings.accessToken) {
      return {
        synced: 0,
        skipped: 0,
        failed: 0,
        message: "Add a Bangumi access token in plugin settings first."
      };
    }
    if (this.settings.collectionTypes.length === 0) {
      return {
        synced: 0,
        skipped: 0,
        failed: 0,
        message: "Select at least one Bangumi collection status to sync."
      };
    }
    const client = new BangumiClient({
      accessToken: this.settings.accessToken,
      userAgent: this.settings.userAgent
    });
    const username = this.settings.username || (await client.getMe()).username;
    const writer = new NoteWriter(this.app, new MarkdownRenderer());
    const seenSubjectIds = /* @__PURE__ */ new Set();
    let synced = 0;
    let skipped = 0;
    let failed = 0;
    for (const collectionType of this.settings.collectionTypes) {
      let collections;
      try {
        collections = await this.fetchAllCollections(
          client,
          username,
          collectionType
        );
      } catch (error) {
        failed += 1;
        console.error(
          `Bangumi Sync failed to fetch collection type ${collectionType}`,
          error
        );
        continue;
      }
      for (const collection of collections) {
        const subjectId = collection.subject.id;
        if (seenSubjectIds.has(subjectId)) {
          skipped += 1;
          continue;
        }
        seenSubjectIds.add(subjectId);
        let episodes = [];
        let episodeSyncError;
        try {
          episodes = await this.fetchAllEpisodeCollections(client, subjectId);
        } catch (error) {
          failed += 1;
          episodeSyncError = error instanceof Error ? error.message : "Unknown episode sync error";
          console.error(
            `Bangumi Sync failed to fetch episodes for subject ${subjectId}`,
            error
          );
        }
        try {
          await writer.writeSubjectNote(this.settings.syncDirectory, {
            collection,
            episodes,
            episodeSyncError
          });
          synced += 1;
        } catch (error) {
          failed += 1;
          console.error(
            `Bangumi Sync failed to write subject ${subjectId}`,
            error
          );
        }
      }
    }
    return {
      synced,
      skipped,
      failed,
      message: `Bangumi Sync finished for ${username}: ${synced} note(s) synced, ${skipped} skipped, ${failed} issue(s).`
    };
  }
  async fetchAllCollections(client, username, collectionType) {
    const collections = [];
    let offset = 0;
    let total = Number.POSITIVE_INFINITY;
    while (offset < total) {
      const page = await client.getCollections({
        username,
        subjectType: ANIME_SUBJECT_TYPE,
        collectionType,
        limit: PAGE_LIMIT,
        offset
      });
      total = page.total;
      collections.push(...page.data);
      if (page.data.length === 0) {
        break;
      }
      offset += page.data.length;
    }
    return collections;
  }
  async fetchAllEpisodeCollections(client, subjectId) {
    const page = await client.getSubjectEpisodeCollections(subjectId);
    return page.data.sort(
      (left, right) => left.episode.sort - right.episode.sort
    );
  }
};

// src/main.ts
var BangumiSyncPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-cw", "Sync Bangumi", () => {
      void this.syncNow();
    });
    this.addCommand({
      id: "sync-now",
      name: "Sync now",
      callback: () => {
        void this.syncNow();
      }
    });
    this.addSettingTab(new BangumiSyncSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async syncNow() {
    try {
      const result = await new SyncService(this.app, this.settings).sync();
      new import_obsidian4.Notice(result.message);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown Bangumi sync error";
      new import_obsidian4.Notice(`Bangumi Sync failed: ${message}`);
      console.error(error);
    }
  }
};
